version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend_api
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    depends_on:
      - mongodb
    volumes:
      - ./temp_uploads:/app/backend/temp_uploads
      - ./uploads:/app/backend/uploads

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db

  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
